version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=mysql://root:123456@172.23.64.1:3306/whatsapp_automation

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend