version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - DATABASE_URL=mysql://usuario:password@127.0.0.1:3306/whatsapp_automation
    network_mode: host  # ⚠️ Muy importante si Redis/MySQL están fuera de Docker

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend