# backend/Dockerfile.backend
FROM node:18

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend .

# Compilar Prisma si es necesario
RUN npx prisma generate

EXPOSE 3001

CMD ["npm", "run", "start"]