version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - DATABASE_URL=mysql://root:123456@host.docker.internal:3306/whatsapp_automation

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend