version: '3.8'

services:
  redis:
    image: redis:alpine    
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=mysql://prisma:oblongo750@localhost:3306/whatsapp_automation      

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
    depends_on:
      - backend